apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: simplenode
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - simplenode.simpleproject-prod.35.195.181.244.xip.io
  - simplenode
  http:
  - route:
    - destination:
        host: simplenode-canary.simpleproject-prod.svc.cluster.local
    - destination:
        host: simplenode-primary.simpleproject-prod.svc.cluster.local
      weight: 100
